import { cdk } from "projen";
// import { cdk, Task } from "projen";
import { NodePackageManager } from "projen/lib/javascript";

const project = new cdk.JsiiProject({
  author: "Tim Hahn",
  authorAddress: "hahntj@gmail.com",
  defaultReleaseBranch: "main",
  jsiiVersion: "~5.3.0",
  name: "projen-utils",
  projenrcTs: true,
  packageManager: NodePackageManager.NPM,
  repositoryUrl: "https://github.com/hahntj/projen-utils.git",

  // set up the package name in package.json
  packageName: "@ncfour/projen-utils",

  // set up the project with a LICENSE and copyright info
  license: "MIT",
  copyrightOwner: "Tim Hahn",
  copyrightPeriod: "2024",

  // eslint options
  eslintOptions: {
    dirs: ["src"],
    prettier: true,
  },

  /* Peer dependencies of this module. */
  // Needed to switch this from deps to peerDeps for 'projen' and 'constructs' when switching to a JSII module
  peerDeps: ["projen", "constructs"],

  /* Build dependencies for this module. */
  // Needed to add peerDeps for 'projen' and 'constructs' to devDeps as well when switching to a JSII module
  devDeps: [
    "projen",
    "constructs",
    "@types/node",
    "@jest/globals",
    "fs",
    "yaml",
  ],

  // Define additional targets beyond JavaScript
  publishToPypi: {
    module: "projen_utils",
    distName: "projen-utils",
  },
});

// HACK: This modifies the filename of the .tgz file generated by jsii-pacmak for JavaScript packages.
//       The long script finds files with an "@" character in them and changes the "@" to a "-".
//       This is NOT needed if using NodePackageManager.NPM in the projects that use this package
//       and install using the bundled/package .tgz filename.
//
// const packageJsTask: Task | undefined  = project.tasks.tryFind("package:js");
// packageJsTask?.exec(`
//   bash -c 'files=$(ls dist/js/*.tgz | grep -E "^(.*)@(.*)\\.tgz");
//   for file in \${files[@]};
//     do newfile=$(echo $file | sed -E "s/^(.*)\\@(.*)\\.tgz$/\\1-\\2.tgz/");
//     echo "moving $file to $newfile";
//     mv $file $newfile;
//   done'
// `);

project.synth();
