import { cdk, github } from "projen";

// import { cdk, Task } from "projen";
import { NodePackageManager } from "projen/lib/javascript";

import {
  DocsIndexSampleFile,
  PreCommitConfigFile,
  PreCommitConfigFileTypes,
  TypedocJson,
} from "./src";

const packageManager: NodePackageManager = NodePackageManager.PNPM;
const packageManagerRunCommand: string = "pnpm";

const project = new cdk.JsiiProject({
  // use this to turn on logging/tracing
  // logging: {
  //   level: LogLevel.DEBUG,
  // },

  author: "Tim Hahn",
  authorAddress: "hahntj@gmail.com",
  defaultReleaseBranch: "main",
  name: "projen-utils",
  projenrcTs: true,
  packageManager: packageManager,
  repositoryUrl: "https://github.com/ncfour-us/projen-utils.git",
  keywords: ["awscdk", "projen", "pre-commit", "typescript", "ESM"],

  // set up the package name in package.json
  packageName: "@ncfour-us/projen-utils",

  // set up the project with a LICENSE and copyright info
  license: "MIT",
  copyrightOwner: "Tim Hahn",
  copyrightPeriod: "2024",

  // eslint options
  eslintOptions: {
    dirs: ["src"],
    prettier: true,
  },

  /* Peer dependencies of this module. */
  // Needed to switch this from deps to peerDeps for 'projen' and 'constructs' when switching to a JSII module
  peerDeps: ["projen", "constructs"],

  /* Build dependencies for this module. */
  // Needed to add peerDeps for 'projen' and 'constructs' to devDeps as well when switching to a JSII module
  devDeps: [
    "projen",
    "constructs",
    "@types/node",
    "@jest/globals",
    "fs",
    "yaml",
    "@eslint/compat",
    "globals",
    "@eslint/js",
    "@eslint/eslintrc",
  ],

  // exclude projen from dependency upgrade checks
  // Upgrades of the projen package require updates to pnpm-lock.yaml
  depsUpgradeOptions: {
    exclude: ["projen"],
  },

  // use "Trusted Publishing" to interact with NPMJS (better than using NPM_TOKENs)
  npmTrustedPublishing: true,

  // use GitHub App credentials instead of a Personal Access Token
  githubOptions: {
    projenCredentials: github.GithubCredentials.fromApp({
      permissions: {
        pullRequests: github.workflows.AppPermission.WRITE,
        contents: github.workflows.AppPermission.WRITE,
      },
    }),
  },

  // Define additional targets beyond JavaScript
  publishToPypi: {
    module: "ncfour_us_projen_utils",
    distName: "ncfour-us-projen-utils",
    trustedPublishing: true,
  },
});

// make sure the sample files used are added to the package contents (and thus available at synth time)
project.compileTask.exec("mkdir -p lib/files");
project.compileTask.exec("cp src/files/* lib/files/.");

new PreCommitConfigFile(project, {
  fileTypes: [PreCommitConfigFileTypes.TYPESCRIPT],
  packageManager: packageManager,
});

new DocsIndexSampleFile(project);

// install typedoc and markdown plugin
project.addDevDeps("typedoc", "typedoc-plugin-markdown");

// create the typedoc.json configuration file for typedoc
new TypedocJson(project, {
  entryPoints: ["./src/index.ts"],
});

// add scripts to run API documentation generation
const buildDocsTask = project.addTask("build:docs", {
  description: "Generate Typedoc documentation",
  exec: `${packageManagerRunCommand} typedoc`,
});

project.addPackageIgnore("docs");

// add API generation to the post-compile processing
project.postCompileTask.addSteps({
  spawn: buildDocsTask.name,
});

// HACK: This modifies the filename of the .tgz file generated by jsii-pacmak for JavaScript packages.
//       The long script finds files with an "@" character in them and changes the "@" to a "-".
//       This is NOT needed if using NodePackageManager.NPM in the projects that use this package
//       and install using the bundled/package .tgz filename.
//
// const packageJsTask: Task | undefined  = project.tasks.tryFind("package:js");
// packageJsTask?.exec(`
//   bash -c 'files=$(ls dist/js/*.tgz | grep -E "^(.*)@(.*)\\.tgz");
//   for file in \${files[@]};
//     do newfile=$(echo $file | sed -E "s/^(.*)\\@(.*)\\.tgz$/\\1-\\2.tgz/");
//     echo "moving $file to $newfile";
//     mv $file $newfile;
//   done'
// `);

// HACK: The code below was written before finding out that the NodePackage project
//       type supports a "npmTrustedPublishing" option.  This option sets up the
//       Github workflow to the equivalent of what was done with patching below.
//
// const releaseFile = project.tryFindObjectFile(".github/workflows/release.yml");
// releaseFile?.patch(
//   JsonPatch.add("/jobs/release_npm/permissions/id-token", "write"),
// );
// releaseFile?.patch(
//   JsonPatch.add(
//     "/jobs/release_npm/steps/10/env/NPM_TRUSTED_PUBLISHER",
//     "${{ vars.NPM_TRUSTED_PUBLISHER }}",
//   ),
// );

project.synth();
