import { cdk, JsonPatch } from "projen";

// import { cdk, Task } from "projen";
import { NodePackageManager } from "projen/lib/javascript";

const project = new cdk.JsiiProject({
  author: "Tim Hahn",
  authorAddress: "hahntj@gmail.com",
  defaultReleaseBranch: "main",
  jsiiVersion: "~5.9.41",
  projenVersion: "^0.99.61",
  name: "projen-utils",
  projenrcTs: true,
  packageManager: NodePackageManager.PNPM,
  repositoryUrl: "git+https://github.com/ncfour-us/projen-utils.git",
  keywords: ["awscdk", "projen", "pre-commit", "typescript", "ESM"],

  // set up the package name in package.json
  packageName: "@ncfour-us/projen-utils",

  // set up the project with a LICENSE and copyright info
  license: "MIT",
  copyrightOwner: "Tim Hahn",
  copyrightPeriod: "2024",

  // eslint options
  eslintOptions: {
    dirs: ["src"],
    prettier: true,
  },

  /* Peer dependencies of this module. */
  // Needed to switch this from deps to peerDeps for 'projen' and 'constructs' when switching to a JSII module
  peerDeps: ["projen", "constructs"],

  /* Build dependencies for this module. */
  // Needed to add peerDeps for 'projen' and 'constructs' to devDeps as well when switching to a JSII module
  devDeps: [
    "projen",
    "constructs",
    "@types/node",
    "@jest/globals",
    "fs",
    "yaml",
    "@eslint/compat",
    "globals",
    "@eslint/js",
    "@eslint/eslintrc",
  ],

  // Define additional targets beyond JavaScript
  publishToPypi: {
    module: "projen_utils",
    distName: "projen-utils",
  },
});

// make sure the sample files used are added to the package contents (and thus available at synth time)
project.compileTask.exec("mkdir -p lib/files");
project.compileTask.exec("cp src/files/* lib/files/.");

// HACK: This modifies the filename of the .tgz file generated by jsii-pacmak for JavaScript packages.
//       The long script finds files with an "@" character in them and changes the "@" to a "-".
//       This is NOT needed if using NodePackageManager.NPM in the projects that use this package
//       and install using the bundled/package .tgz filename.
//
// const packageJsTask: Task | undefined  = project.tasks.tryFind("package:js");
// packageJsTask?.exec(`
//   bash -c 'files=$(ls dist/js/*.tgz | grep -E "^(.*)@(.*)\\.tgz");
//   for file in \${files[@]};
//     do newfile=$(echo $file | sed -E "s/^(.*)\\@(.*)\\.tgz$/\\1-\\2.tgz/");
//     echo "moving $file to $newfile";
//     mv $file $newfile;
//   done'
// `);

const releaseFile = project.tryFindObjectFile('.github/workflows/release.yml');
releaseFile?.patch(JsonPatch.add('/jobs/release_npm/steps/10/env/NPM_TRUSTED_PUBLISHER', '${{ vars.NPM_TRUSTED_PUBLISHER }}' ));
console.log(`releaseFile: ${releaseFile?.path}`);

project.synth();
