// Copyright (c) 2024 Tim Hahn

import { javascript, typescript, JsonPatch } from "projen";

export interface CommandParameters {
  readonly name: string;
  readonly file: string;
}

export interface TypeScriptESMProjectOptions
  extends typescript.TypeScriptProjectOptions {
  readonly addVersionFile?: boolean;
  readonly commands?: CommandParameters[];
}

/**
 * TypeScript ESM project
 * @pjid typescript-esm
 */
export class TypeScriptESMProject extends typescript.TypeScriptProject {
  constructor(options: TypeScriptESMProjectOptions) {
    let additionalDevDeps: string[] = ["tsx"];
    additionalDevDeps = additionalDevDeps.concat(
      options.devDeps ? options.devDeps : [],
    );

    // create a new options instance, copying the input values
    // and over-riding those that need to be set for ESM
    const typeScriptProjectOptions: typescript.TypeScriptProjectOptions = {
      ...options,
      // start clauses added to enable ESM module usage
      devDeps: additionalDevDeps,
      minNodeVersion: "18.0.0",
      workflowNodeVersion: "18.x",
      tsconfig: {
        compilerOptions: {
          moduleResolution: javascript.TypeScriptModuleResolution.NODE_NEXT,
          module: "nodenext",
          lib: ["DOM", "esnext"],
          target: "esnext",
        },
      },

      jestOptions: {
        jestConfig: {
          extensionsToTreatAsEsm: [".ts"],
          moduleNameMapper: {
            "^(\\.{1,2}/.*)\\.js$": "$1",
          },
          transform: {
            "^.+\\.(mt|t|cj|j)s$": new javascript.Transform("ts-jest", {
              useESM: true,
              tsconfig: "tsconfig.dev.json",
            }),
          },
        },
      },
      // end clauses added to enable ESM module usage
    };

    // construct the project instance (TypeScriptProject)
    super(typeScriptProjectOptions);

    // start project adjustments to enable ESM module usage

    // set "type": "module" in package.json
    this.package.addField("type", "module");
    // project.package.file.addOverride('type', 'module');

    // set NODE_OPTIONS environment variable when running jest during tests
    this.testTask.env("NODE_OPTIONS", "--experimental-vm-modules");

    // patch package.json to remove a transform inserted by the TypeScriptProject package
    // const packageJson = this.tryFindObjectFile("package.json");
    // packageJson?.patch(JsonPatch.remove("/jest/transform/^.+\\.[t]sx?$"));
    this.package.file.patch(JsonPatch.remove("/jest/transform/^.+\\.[t]sx?$"));

    // getting ts-node to work in ESM mode just wasn't working.  Switch to using tsx to run the projen generator
    this.defaultTask?.reset(
      `tsx --tsconfig ${this.tsconfigDev.file.path} .projenrc.ts`,
    );

    // end project adjustments to enable ESM module usage

    // start additional features

    // Optionally add a version.ts file
    if (options.addVersionFile) {
      // use this method to create a version.ts file which includes the version number from package.json
      // import of JSON files is still experimental (as of December 2023) so don't use it - and importing JSON
      // requires using ESM modules.  It is not possible in CommonJS.
      this.addScripts({
        "create-version":
          "echo '// Generated by pre-compile processing' >src/version.ts;" +
          " node -p \"'export const LIB_VERSION = ' + JSON.stringify(require('./package.json').version) + ';'\" >>src/version.ts",
      });

      const createVersion = this.addTask("create-version", {
        description:
          "customized task to run a script which generates version.ts",
        exec: "npm run create-version",
      });

      // this adds the create-version task as a sub-task of the pre-created preCompileTask.
      this.preCompileTask.spawn(createVersion);

      // add src/version.ts to the .gitignore file so that it is not stored in the repo
      this.addGitIgnore("src/version.ts");
    }

    // Optionally add additional commands to package.json and the install
    if (options.commands) {
      for (const command of options.commands) {
        // the program can be run by running 'yarn run <command.name>' or 'npm run <command.name>'
        this.addScripts({ [command.name]: `node ./lib/${command.file}` });

        // this adds a '<command.name>' command when the package is installed somewhere
        this.addBins({ [command.name]: `./lib/${command.file}` });
      }
    }
    // end additional features
  }
}
